# Generated by Django 5.0 on 2025-11-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feeds/')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('feed_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('duplicate', 'Duplicate'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
