# Generated by Django 5.0 on 2025-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_ru', 'name_en']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name_ru', 'name_en']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name_en')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
