# Generated by Django 5.0 on 2025-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('limit', models.PositiveIntegerField(default=1000)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
